### ISSUE TITLE
Error al generar scripts con Centos 7.5 y Node 6.14

### ISSUE THREAD

**Issue by 11sma** [gencat/ICGC-createsprites#1]
Hola, estoy probando el generador de sprites. He podido descargarme bien el proyecto, hacer npm install pero al ejecutar npm createSprites.js error. Me falta instalar algo? La traza que objtengo es la siguiente:

[root ICGC-createsprites]# node createSprites.js
module.js:604
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/ICGC-createsprites/node_modules/mapnik/lib/binding/mapnik.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/ICGC-createsprites/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)

Muchas gracias por adelantado

**Comment by bolollo** [comment]
Hola, ¿que sistema operativo tienes? y que versión de nodejs ?
Yo lo he probado en Ubuntu 16.04 con nodejs 6.9.5 y me ha funcionado.

**Comment by 11sma** [comment]
Hola, gracias por contestar, lasa versiones que tengo son:

[root~]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
[root~]# node -v
v6.14.2

**Comment by 11sma** [comment]
Hola, gracias por contestar, lasa versiones que tengo son:

[root~]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
[root~]# node -v
v6.14.2

**Comment by bolollo** [comment]
Hola, he probado a crear una maquina virtual en virtualBox con el centos 7.5 y el node v6.14.2 y efectivamente da error. Al ser una maquina virtual no la tengo registrada en redhat y no puedo hacer un yum install, pero podrías intentar 

- yum install libstdc++ 

Aquí explican algo de como solucionarlo https://www.linuxquestions.org/questions/linux-newbie-8/searching-for-glibcxx_3-4-20-a-4175552395/

También he intentado instalar la última version del libstdc++ via rpm (la he descargado de https://pkgs.org/download/libstdc++ version ALT Linux Sisyphus no de centos por que tiene un paquete muy viejo) pero al intentar instalarla me da un error de dependencia del anaconda.

**Comment by 11sma** [comment]
Nota: Probé el post que me pasaste y alguna solución más y para esta versión de centos/npm no me funcionó.

Muchas gracais en todo caso :)
